[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefer-offline --no-audit"

# Enable Next.js runtime for Netlify
[functions]
  directory = ".netlify/functions"

# Redirect rules for i18n routing
[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = false

# Handle locale-based routing for all pages
[[redirects]]
  from = "/en/*"
  to = "/en/:splat"
  status = 200

[[redirects]]
  from = "/vi/*"
  to = "/vi/:splat"
  status = 200

# Handle Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Handle NextAuth API routes specifically
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/en/404"
  status = 404

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000" 